version: "2"
services:
  campai-mongo:
    container_name: mongodb-social-network
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  campai-back-app:
    container_name: campai-node-back
    restart: always
    environment:
      - PORT=8080
      - DATABASE_HOST=campai-mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=social-network
      - DB_MONGODB_USER=admin
      - DB_MONGODB_PASS=admin
      - WAIT_HOSTS=campai-mongo:27017
      - API_KEY_STREAM=33rpj3hmmh35
      - API_SECRET_STREAM=yfu6hajqvrdbxgfrun85tuqxycexzbfeefhjer4gr6k6qserjapjpt8kv3sqawrx
      - API_ID_STREAM=48095
      - DEFAULT_ENDPOINT=https://us-east-api.stream-io-api.com/api/v1.0/
      - SECRET=secret
    build: 
      context: ./back-end
    ports:
      - "8080:8080"
    links:
      - campai-mongo
    depends_on:
      - campai-mongo
  campai-front-react:
    container_name: campai-react-front
    restart: always
    build: ./front-end
    ports:
      - "3000:3000"